# SPDX-FileCopyrightText: 2024 The DeckCheatz Developers
#
# SPDX-License-Identifier: Apache-2.0

---
name: Nightly builder for Linux

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-nightlies-linux:
    name: Nightly builds for Linux (x86_64-unknown-linux-musl)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.1.4
      - name: Cache Rust assets
        id: rust-cache
        uses: Swatinem/rust-cache@v2
      - name: Configure Rust
        if: ${{ steps.rust-cache.outputs.cache-hit != 'true' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: llvm-tools-preview
          override: true
          target: x86_64-unknown-linux-musl
          profile: minimal
      - name: Install Cross
        if: ${{ steps.rust-cache.outputs.cache-hit != 'true' }}
        uses: brndnmtthws/rust-action-cargo-binstall@v1.1.0
        with:
          packages: cross
      - name: Build for x86_64-unknown-linux-musl
        id: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: >-
            --all --locked --verbose --target=x86_64-unknown-linux-musl
          use-cross: true
      - name: Zip up the artifacts
        id: zipup
        if: ${{ steps.build.outcome == 'success' }}
        run: zip ${{ github.workspace }}/steam-toybox-nightly-x86_64-unknown-linux-musl.zip ${{ github.workspace }}/target/x86_64-unknown-linux-musl/debug/stoybox
      - name: Create nightly release
        continue-on-error: true
        if: ${{ steps.zipup.outcome == 'success' }}
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: true
          body: "Nightly build of `DeckCheatz` for target: x86_64-unknown-linux-musl"
          release_name: steam-toybox-nightly-x86_64-unknown-linux-musl
          tag_name: steam-toybox-nightly-x86_64-unknown-linux-musl
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload debug nightly build
        run: gh release upload steam-toybox-nightly-x86_64-unknown-linux-musl ${{ github.workspace }}/steam-toybox-nightly-x86_64-unknown-linux-musl.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
