# SPDX-FileCopyrightText: 2024 The DeckCheatz Developers
#
# SPDX-License-Identifier: Apache-2.0

---
name: Release Builders

on:
  workflow_run:
    workflows: [CI test workflow]
    types: [completed]
    branches: [main]

permissions:
  contents: write

jobs:
  build-linux-release:
    if: ${{ startsWith(github.ref, 'refs/tags/') && github.event.workflow_run.conclusion
      == 'success' }}
    uses: ./.github/workflows/ci-release-builds-linux.yml
    secrets: inherit
