# SPDX-FileCopyrightText: 2024 The DeckCheatz Developers
#
# SPDX-License-Identifier: Apache-2.0

---
name: CI Tests

on:
  push:
    paths: ["src/**", "Cargo.toml", "Cargo.lock", "rust-toolchain.toml", "*.nix"]
  workflow_dispatch:
  workflow_run:
    workflows: ["Update Flatpak Cargo lockfile"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test-linux:
    uses: ./.github/workflows/ci-tests-linux.yml
    secrets: inherit

  test-nix-pm:
    uses: ./.github/workflows/ci-tests-nix.yml
    secrets: inherit
