# SPDX-FileCopyrightText: 2024-2025 The DeckCheatz Developers
#
# SPDX-License-Identifier: Apache-2.0
name: Update Flatpak Cargo lockfile
on:
  push:
    paths: ["Cargo.lock"]
  workflow_dispatch:
jobs:
  update-flatpak-cargo-data:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git config --global user.email "github-actions+deckcheatz@noreply.github.com"
          git config --global user.name "GitHub Actions [Deckcheatz]"
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: actions/setup-python@v6
      - run: pip install --user toml aiohttp
      - run: |
          (./script/flatpak-builder-tools/cargo/flatpak-cargo-generator.py -o ./build-aux/flatpak/generated-cargo-sources.json ./Cargo.lock \
          && git add -f ./build-aux/flatpak/generated-cargo-sources.json \
          && git commit -m "chore(flatpak): Update generated-cargo-sources.json for Flatpak usage" \
          && git push origin ${{github.ref}}:${{github.ref}}) \
          || exit 0
